version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: delivery-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - delivery-db:/var/lib/delivery-db
volumes:
  delivery-db:
